// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcktflhmkkegvekxuzji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJja3RmbGhta2tlZ3Zla3h1emppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODQyNjYsImV4cCI6MjA2NTE2MDI2Nn0.V_pbox-ldJyEKeoBJr2AlJhVO04_2A99Kz3YfsO8HHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);