name: Build iOS App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Install Capacitor CLI
        run: npm install --global @capacitor/cli

      - name: Add iOS Platform
        run: npx cap add ios

      - name: Build iOS app
        run: |
          cd ios
          xcodebuild -scheme App -sdk iphoneos -configuration Release archive -archivePath ${{ github.workspace }}/build/App.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath ${{ github.workspace }}/build/App.xcarchive -exportOptionsPlist ios/App/exportOptions.plist -exportPath ${{ github.workspace }}/build/IPA

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Therapod-iOS-App
          path: build/IPA/*.ipa
